# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b867014276c8576d985a7848a59c33e62af64dd62f51fceb3c58ebadce64669d4cfc122c492d34a995ec5c0c31deaeccdfa1143e193c76341bac4e9fbe9e3b97

test:
  secret_key_base: 926a0b83fc5e3169fc868ef220fd3080e9f02592a2645d161d154b8b9de0db7175552a64c72bd1eba27ac6565347c8442746ef583440940900dd56a91d95f576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
